language: ruby
rvm:
  - 2.5.0

before_install:
  gem install bundler

install:
  bundle install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - rails server
  - sleep 3

script:
  rails db:setup RAILS_ENV=test
  rails db:migrate RAILS_ENV=test
