language: ruby
rvm:
  - 2.5.0

script:
    - mkdir -p spec && bundle exec rspec spec

install:
  - bundle install

before_install:
  - gem install bundler

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - rails db:setup RAILS_ENV=test
  - rails db:migrate RAILS_ENV=test
