version: '3.7'
services:
  db:
    image: postgres:10.4
    ports:
      - "5432:5432"

  web:
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ".:/app"
